### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by paskal**
Hi @phoinixi!

This PR:
- bump package version
- bump dependencies versions
- bump fontawesome
- add .gitignore from GitHub NodeJS gitignore example
- prettify CSS formatting
- remove one unused option from CSS
- fix `summary` rendering to expand HTML inside it:
    Before:
    before
    After:
    after

Feel free to review and merge.

### CODE REVIEW

**Comment by phoinixi** [comment]
great, thanks for that

**Comment by paskal** [comment]
@phoinixi would you be so kind as to release 0.3.0 [to npm](https://www.npmjs.com/package/jsonresume-theme-spartan)?

**Comment by paskal** [comment]
Unrelated, but I found out that in [your npm profile](https://www.npmjs.com/~francescoes) there is a link to @francescoes instead of to @phoinixi.

**Comment by Francescoes** [comment]
I haven’t an account with username francescoes on npmjs.com. That’s my username only on GitHub.



Da: Dmitry Verkhoturov<mailto:notifications@github.com>
Inviato: martedì 14 gennaio 2020 18:21
A: phoinixi/jsonresume-theme-spartan<mailto:jsonresume-theme-spartan@noreply.github.com>
Cc: Francesco Esposito<mailto:francescoesposito4@outlook.com>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [phoinixi/jsonresume-theme-spartan] Multiple fixes (#4)


Unrelated, but I found out that in your npm profile<https://www.npmjs.com/~francescoes> there is a link to @Francescoes<https://github.com/Francescoes> instead of to @phoinixi<https://github.com/phoinixi>.

**Comment by paskal** [comment]
@Francescoes my apologies for pinging you, @phoinixi got the same name and linked your GitHub profile by accident from his npmjs.com account:) I completely forgot that writing your username would send a notification.

**Comment by phoinixi** [comment]
That was my previous username on github, hence the confusion, thanks
anyway, I will fix that :)

**Comment by paskal** [comment]
@phoinixi please please please upload new package to npm, it's so sad all the changes are already in place but I can't utilize them:)

**Comment by paskal** [comment]
@phoinixi still waiting for 0.3.0 release on [npmjs](https://www.npmjs.com/package/jsonresume-theme-spartan).

**Comment by phoinixi** [comment]
Done

**Comment by Francescoes** [comment]
I am still in cc :). Can you start a new conversation?



Inviato da smartphone Samsung Galaxy.


-------- Messaggio originale --------
Da: Francesco Esposito <notifications@github.com>
Data: 16/01/20 18:31 (GMT+01:00)
A: phoinixi/jsonresume-theme-spartan <jsonresume-theme-spartan@noreply.github.com>
Cc: Francesco Esposito <francescoesposito4@outlook.com>, Mention <mention@noreply.github.com>
Oggetto: Re: [phoinixi/jsonresume-theme-spartan] Multiple fixes (#4)

Done

**Pull request merged**
